language: python

python:
- "2.7"
compiler: clang
env:
- CC="clang" CXX="clang++" LDFLAGS="-fuse-ld=lld"

dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - liblapack3

install:
  - pip install numpy==1.14.2 cython==0.28.2 pytest==3.5.1 scikit-learn==0.19.1 scipy==1.0.1
script:
  - pwd
  - python setup.py install
  - cd tsne/tests
  - py.test -s -vv
